### ISSUE TITLE
[Enhancement] Add an option to configure the frequency at which Nagios commands are executed

### ISSUE THREAD

**Issue by remyduthu** [bleemeo/glouton#19]
It would be nice to be able to configure how often Nagios tests are run. For example, for data that only changes once a month. Is it possible to add this parameter?

Thanks 🙌

**Comment by ozon2** [comment]
Hi, this feature was added in the latest release, you can now specify the interval between checks in seconds with the `interval` parameter: https://docs.bleemeo.com/metrics-sources/custom#reference-for-custom-check
```yaml
service:
  - id: "my_nagios_check"
    interval: 60
    check_type: "nagios"
    check_command: "/path/to/bin --with-option"
```
